export const BUILD_DIRS = [
  "node_modules",
  "dist",
  "build",
  ".svelte-kit",
  ".svelte",
  ".next",
  ".nuxt",
  "out",
  ".output",
  ".vercel",
  ".netlify",
  ".astro",
  ".angular",
  ".angular/cache",
  ".solid",
  ".docusaurus",
  ".vite",
  ".cache",
  ".parcel-cache",
  ".webpack",
  ".rollup.cache",
  ".rpt2_cache",
  ".swc",
  ".eslintcache",
  ".stylelintcache",
  ".sass-cache",
  ".tmp",
  "tmp",
  "temp",
  "coverage",
  ".nyc_output",
  "storybook-static",
  ".storybook-out",
  ".turbo",
  ".rush",
  ".firebase",
  ".serverless",
  "android/.gradle",
  "android/build",
  "android/app/build",
  "ios/Pods",
  "ios/build",
  ".expo",
  ".expo-shared",
  "lib",
  "es",
  "cjs",
  "umd",
] as const;

export const CACHE_DIRS = [
  ".pnpm-store",
  ".pnpm-debug.log",
  ".yarn/cache",
  ".yarn/unplugged",
  ".yarn/install-state.gz",
  ".yarn/build-state.yml",
  ".npm",
  "node_modules/.cache",
] as const;

export const CUSTOM_DIRS = [
  // Add project-specific folders/files to remove during torch.
  // Examples:
  // "apps/web/.next",
  // "services/api/tmp",
  // "custom_dir/",
] as const;
